"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
const channels = {
    listProjects: 'projects:list',
    createProject: 'projects:create',
    chooseAndOpenProject: 'projects:choose-and-open',
    getProject: 'projects:get',
    duplicateProject: 'projects:duplicate',
    archiveProject: 'projects:archive',
    refreshProject: 'projects:refresh',
    getStoryboard: 'storyboard:get',
    chooseAndImportStoryboard: 'storyboard:choose-and-import',
    createAssetTask: 'assets:create-task',
    updateAssetStatus: 'assets:update-status',
    chooseAndImportAssetMedia: 'assets:choose-and-import-media',
    importAssetMediaPath: 'assets:import-media-path',
    getFlowWorkspace: 'flow:get',
    chooseFlowWatchDirectory: 'flow:choose-watch-directory',
    scanFlowCandidates: 'flow:scan-candidates',
    prepareFlowAssetTask: 'flow:prepare-task',
    selectFlowCandidate: 'flow:select-candidate',
    rejectFlowCandidate: 'flow:reject-candidate',
    copyText: 'system:copy-text',
    exportStoryboardRenderInput: 'render:export-storyboard-input',
    getVoiceWorkspace: 'voice:get',
    syncNarrationSegments: 'voice:sync-segments',
    chooseAndImportNarrationAudio: 'voice:choose-and-import-audio',
    generateNarrationSegment: 'voice:generate-segment',
    generateMissingNarration: 'voice:generate-missing',
    chooseAndImportCaptions: 'voice:choose-and-import-captions',
    fitTimelineToNarration: 'voice:fit-timeline',
    getTimelineWorkspace: 'timeline:get',
    updateCaptionCue: 'timeline:update-caption',
    updateShotAudio: 'timeline:update-shot-audio',
    chooseAndImportTimelineAudio: 'timeline:import-audio',
    generateCaptionsFromNarration: 'timeline:generate-captions',
    getEditorialWorkspace: 'editorial:get',
    saveEditorialDocument: 'editorial:save-document',
    selectTopicCandidate: 'editorial:select-topic',
    selectThesisCandidate: 'editorial:select-thesis',
    saveOutline: 'editorial:save-outline',
    getReviewWorkspace: 'review:get',
    approveGate: 'review:approve-gate',
    revokeGate: 'review:revoke-gate',
    queueRender: 'render:queue',
    cancelJob: 'render:cancel-job',
    retryJob: 'render:retry-job',
    chooseAndAttachRenderOutput: 'render:choose-and-attach-output',
    getSystemDiagnostics: 'system:diagnostics',
    chooseProjectBackupDirectory: 'system:backup-project',
    codexReadAccount: 'codex:account-read',
    codexStartBrowserLogin: 'codex:login-browser',
    codexStartDeviceLogin: 'codex:login-device',
    codexListModels: 'codex:model-list',
    codexReadRateLimits: 'codex:rate-limits-read',
    codexStartOrResumeThread: 'codex:thread-start-or-resume',
    codexStartTurn: 'codex:turn-start',
    codexRunEditorialStage: 'codex:editorial-stage-run',
    codexInterruptTurn: 'codex:turn-interrupt',
    codexGetWorkspace: 'codex:workspace-get',
    codexUpdateSettings: 'codex:settings-update',
    codexRespondServerRequest: 'codex:server-request-respond',
    openExternalUrl: 'system:open-external-url',
    menuAction: 'system:menu-action',
    codexEvent: 'codex:event',
};
const api = {
    runtime: 'electron',
    version: 14,
    listProjects: () => electron_1.ipcRenderer.invoke(channels.listProjects),
    createProject: (input) => electron_1.ipcRenderer.invoke(channels.createProject, input),
    chooseAndOpenProject: () => electron_1.ipcRenderer.invoke(channels.chooseAndOpenProject),
    getProject: (projectId) => electron_1.ipcRenderer.invoke(channels.getProject, projectId),
    duplicateProject: (projectId) => electron_1.ipcRenderer.invoke(channels.duplicateProject, projectId),
    archiveProject: (projectId) => electron_1.ipcRenderer.invoke(channels.archiveProject, projectId),
    refreshProject: (projectId) => electron_1.ipcRenderer.invoke(channels.refreshProject, projectId),
    getStoryboard: (projectId) => electron_1.ipcRenderer.invoke(channels.getStoryboard, projectId),
    chooseAndImportStoryboard: (projectId) => electron_1.ipcRenderer.invoke(channels.chooseAndImportStoryboard, projectId),
    createAssetTask: (projectId, input) => electron_1.ipcRenderer.invoke(channels.createAssetTask, projectId, input),
    updateAssetStatus: (projectId, assetId, input) => electron_1.ipcRenderer.invoke(channels.updateAssetStatus, projectId, assetId, input),
    chooseAndImportAssetMedia: (projectId, assetId) => electron_1.ipcRenderer.invoke(channels.chooseAndImportAssetMedia, projectId, assetId),
    importDroppedAssetMedia: (projectId, assetId, file) => electron_1.ipcRenderer.invoke(channels.importAssetMediaPath, projectId, assetId, electron_1.webUtils.getPathForFile(file)),
    getFlowWorkspace: (projectId) => electron_1.ipcRenderer.invoke(channels.getFlowWorkspace, projectId),
    chooseFlowWatchDirectory: (projectId) => electron_1.ipcRenderer.invoke(channels.chooseFlowWatchDirectory, projectId),
    scanFlowCandidates: (projectId) => electron_1.ipcRenderer.invoke(channels.scanFlowCandidates, projectId),
    prepareFlowAssetTask: (projectId, input) => electron_1.ipcRenderer.invoke(channels.prepareFlowAssetTask, projectId, input),
    selectFlowCandidate: (projectId, candidateId, assetId) => electron_1.ipcRenderer.invoke(channels.selectFlowCandidate, projectId, candidateId, assetId),
    rejectFlowCandidate: (projectId, candidateId) => electron_1.ipcRenderer.invoke(channels.rejectFlowCandidate, projectId, candidateId),
    copyText: (value) => electron_1.ipcRenderer.invoke(channels.copyText, value),
    exportStoryboardRenderInput: (projectId) => electron_1.ipcRenderer.invoke(channels.exportStoryboardRenderInput, projectId),
    getVoiceWorkspace: (projectId) => electron_1.ipcRenderer.invoke(channels.getVoiceWorkspace, projectId),
    syncNarrationSegments: (projectId) => electron_1.ipcRenderer.invoke(channels.syncNarrationSegments, projectId),
    chooseAndImportNarrationAudio: (projectId, segmentId) => electron_1.ipcRenderer.invoke(channels.chooseAndImportNarrationAudio, projectId, segmentId),
    generateNarrationSegment: (projectId, input) => electron_1.ipcRenderer.invoke(channels.generateNarrationSegment, projectId, input),
    generateMissingNarration: (projectId, input) => electron_1.ipcRenderer.invoke(channels.generateMissingNarration, projectId, input),
    chooseAndImportCaptions: (projectId) => electron_1.ipcRenderer.invoke(channels.chooseAndImportCaptions, projectId),
    fitTimelineToNarration: (projectId) => electron_1.ipcRenderer.invoke(channels.fitTimelineToNarration, projectId),
    getTimelineWorkspace: (projectId) => electron_1.ipcRenderer.invoke(channels.getTimelineWorkspace, projectId),
    generateCaptionsFromNarration: (projectId) => electron_1.ipcRenderer.invoke(channels.generateCaptionsFromNarration, projectId),
    updateCaptionCue: (projectId, captionId, input) => electron_1.ipcRenderer.invoke(channels.updateCaptionCue, projectId, captionId, input),
    updateShotAudio: (projectId, shotId, input) => electron_1.ipcRenderer.invoke(channels.updateShotAudio, projectId, shotId, input),
    chooseAndImportTimelineAudio: (projectId, role) => electron_1.ipcRenderer.invoke(channels.chooseAndImportTimelineAudio, projectId, role),
    getEditorialWorkspace: (projectId) => electron_1.ipcRenderer.invoke(channels.getEditorialWorkspace, projectId),
    saveEditorialDocument: (projectId, document, content) => electron_1.ipcRenderer.invoke(channels.saveEditorialDocument, projectId, document, content),
    selectTopicCandidate: (projectId, candidateId, input) => electron_1.ipcRenderer.invoke(channels.selectTopicCandidate, projectId, candidateId, input),
    selectThesisCandidate: (projectId, candidateId, statement) => electron_1.ipcRenderer.invoke(channels.selectThesisCandidate, projectId, candidateId, statement),
    saveOutline: (projectId, input) => electron_1.ipcRenderer.invoke(channels.saveOutline, projectId, input),
    getReviewWorkspace: (projectId) => electron_1.ipcRenderer.invoke(channels.getReviewWorkspace, projectId),
    approveGate: (projectId, gate, note) => electron_1.ipcRenderer.invoke(channels.approveGate, projectId, gate, note),
    revokeGate: (projectId, gate, note) => electron_1.ipcRenderer.invoke(channels.revokeGate, projectId, gate, note),
    queueRender: (projectId, target) => electron_1.ipcRenderer.invoke(channels.queueRender, projectId, target),
    cancelJob: (projectId, jobId) => electron_1.ipcRenderer.invoke(channels.cancelJob, projectId, jobId),
    retryJob: (projectId, jobId) => electron_1.ipcRenderer.invoke(channels.retryJob, projectId, jobId),
    chooseAndAttachRenderOutput: (projectId, jobId) => electron_1.ipcRenderer.invoke(channels.chooseAndAttachRenderOutput, projectId, jobId),
    getSystemDiagnostics: () => electron_1.ipcRenderer.invoke(channels.getSystemDiagnostics),
    chooseProjectBackupDirectory: (projectId) => electron_1.ipcRenderer.invoke(channels.chooseProjectBackupDirectory, projectId),
    codexReadAccount: () => electron_1.ipcRenderer.invoke(channels.codexReadAccount),
    codexStartBrowserLogin: () => electron_1.ipcRenderer.invoke(channels.codexStartBrowserLogin),
    codexStartDeviceLogin: () => electron_1.ipcRenderer.invoke(channels.codexStartDeviceLogin),
    codexListModels: () => electron_1.ipcRenderer.invoke(channels.codexListModels),
    codexReadRateLimits: () => electron_1.ipcRenderer.invoke(channels.codexReadRateLimits),
    codexStartOrResumeThread: (projectId) => electron_1.ipcRenderer.invoke(channels.codexStartOrResumeThread, projectId),
    codexGetWorkspace: (projectId) => electron_1.ipcRenderer.invoke(channels.codexGetWorkspace, projectId),
    codexUpdateSettings: (projectId, input) => electron_1.ipcRenderer.invoke(channels.codexUpdateSettings, projectId, input),
    codexStartTurn: (projectId, input) => electron_1.ipcRenderer.invoke(channels.codexStartTurn, projectId, input),
    codexRunEditorialStage: (projectId, input) => electron_1.ipcRenderer.invoke(channels.codexRunEditorialStage, projectId, input),
    codexInterruptTurn: (projectId) => electron_1.ipcRenderer.invoke(channels.codexInterruptTurn, projectId),
    codexRespondServerRequest: (id, result) => electron_1.ipcRenderer.invoke(channels.codexRespondServerRequest, id, result),
    openExternalUrl: (url) => electron_1.ipcRenderer.invoke(channels.openExternalUrl, url),
    onMenuAction: (listener) => {
        const handler = (_event, action) => listener(action);
        electron_1.ipcRenderer.on(channels.menuAction, handler);
        return () => electron_1.ipcRenderer.removeListener(channels.menuAction, handler);
    },
    onCodexEvent: (listener) => {
        const handler = (_event, payload) => listener(payload);
        electron_1.ipcRenderer.on(channels.codexEvent, handler);
        return () => electron_1.ipcRenderer.removeListener(channels.codexEvent, handler);
    },
};
electron_1.contextBridge.exposeInMainWorld('narra', api);
