export const IPC_CHANNELS = {
  listProjects: 'projects:list',
  createProject: 'projects:create',
  chooseAndOpenProject: 'projects:choose-and-open',
  getProject: 'projects:get',
  duplicateProject: 'projects:duplicate',
  archiveProject: 'projects:archive',
  refreshProject: 'projects:refresh',
  getStoryboard: 'storyboard:get',
  chooseAndImportStoryboard: 'storyboard:choose-and-import',
  createAssetTask: 'assets:create-task',
  updateAssetStatus: 'assets:update-status',
  chooseAndImportAssetMedia: 'assets:choose-and-import-media',
  importAssetMediaPath: 'assets:import-media-path',
  exportStoryboardRenderInput: 'render:export-storyboard-input',
} as const;
